name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
      - uses: actions/checkout@v2 # Adds a step to checkout the repository code

      - name: Build C#
        run: dotnet build
      - name: Test C#
        run: dotnet test

      - name: Build TS
        run: |
          cd DotnetTemplate.Web
          npm ci
      - name: Test TS
        run: |
          cd DotnetTemplate.Web
          npm t
          npm run lint
      - name: Linting for TS
        run: npm run lint
